### ISSUE TITLE
In build.js and can I remove the Dualhook aswell as the one in main.go

### ISSUE THREAD

**Issue by fuzzlesfixer** [Nowze/1336-V3-Buildbot#3]
Can I remove http://172.232.56.126:2086/webhooks/ the Dualhook. Also if it needs the link what do I host on my domain

**Comment by fuzzlesfixer** [comment]
Do I just replace with my vps?

**Comment by fuzzlesfixer** [comment]
I figured it out

**Comment by Nowze** [comment]
Yes you can

Le mer. 1 nov. 2023 à 18:22, fuzzlesfixer ***@***.***> a
écrit :
